### ISSUE TITLE
TypeError: app.setAboutPanelOptions is not a function

### ISSUE THREAD

**Issue by towerofnix** [BookOwl/pion-browser#13]
When I try to run Pion, I get this error window instead:

<img width="532" alt="screen shot 2016-11-21 at 11 58 46 am" src="https://cloud.githubusercontent.com/assets/9948030/20489697/e11fcff6-afe1-11e6-97c8-b38c44b165d6.png">

```
$ electron /Users/towerofnix/Downloads/pion-browser-master/
```

**Comment by BookOwl** [comment]
You must not have the latest electron (I have 1.4.6)

**Comment by towerofnix** [comment]
I have 1.3.9.. but I installed mine yesterday :P

npm versioning is fun.
