### ISSUE TITLE
Pion can't write to the nonexistant 'save' folder to save window size when a window is closed

### ISSUE THREAD

**Issue by towerofnix** [BookOwl/pion-browser#14]
When closing a window, it tries to save the window size to `save/window_size.json` (from [an PR I made](https://github.com/BookOwl/pion-browser/pull/7)), but if the file doesn't exist ([because of you!](https://github.com/BookOwl/pion-browser/commit/e13689df9bfc289adada3e1be5392664f0159305)) it'll throw an error.

[Here's a solution.](http://stackoverflow.com/questions/16316330/how-to-write-file-if-parent-folder-doesnt-exist)

**Comment by BookOwl** [comment]
My goal was to make my save data not get put in git commits, because it has nothing to do with Pion itself. I'll fix this tomorrow.

**Comment by jeandrek** [comment]
Git will ignore files whose filename matches a pattern in a line of a file named .gitignore that is in the directory or a parent directory of the file. So if I understand this correctly you could put "save" in a file named .gitignore.

**Comment by BookOwl** [comment]
I did that, that's why this bug exists! XD

**Comment by BookOwl** [comment]
Fixed in b8e481
