### ISSUE TITLE
Use custom toolbar

### ISSUE THREAD

**Issue by towerofnix** [BookOwl/pion-browser#6]
At the moment I get the default Electron toolbar and titlebar:

![screen shot 2015-12-04 at 6 36 24 pm](https://cloud.githubusercontent.com/assets/9948030/11603092/a2711a18-9ab5-11e5-8031-7bb88b8048f1.png)
![screen shot 2015-12-04 at 6 36 33 pm](https://cloud.githubusercontent.com/assets/9948030/11603093/a28ca364-9ab5-11e5-8a08-79bcf3afffb6.png)

It should be a custom toolbar for Pion.

**Comment by jeandrek** [comment]
:+1:

**Comment by jeandrek** [comment]
you can see Electron docs at http://electron.atom.io/docs/v0.35.0/  
<sub>(in case @BookOwl didn't know even though he probably did)</sub>

**Comment by BookOwl** [comment]
I am using a custom toolbar...
Are you using 1.2?

**Comment by towerofnix** [comment]
I'm using the most up-to-date sync'd version of Pion at that date. :package:

**Comment by BookOwl** [comment]
I fixed this too.
