### ISSUE TITLE
Can't install pion

### ISSUE THREAD

**Issue by 439bananas** [BookOwl/pion-browser#8]
Can you help me?

**Comment by BookOwl** [comment]
Did you follow [these instructions](https://github.com/BookOwl/pion-browser/wiki/Installing)? What are you having trouble with?

**Comment by 439bananas** [comment]
installing it using the commands.

**Comment by towerofnix** [comment]
Did you actually run the commands? If so, are you getting any error messages?

**Comment by 439bananas** [comment]
Yes. It's saying that the thing's not found.

**Comment by towerofnix** [comment]
"the thing"? Could you copy and paste all the output to GitHub?

**Comment by BookOwl** [comment]
What thing?

**Comment by 439bananas** [comment]
I've forgotten. :P

**Comment by BookOwl** [comment]
Try it again, and paste the output here.

**Comment by DemiLovato69** [comment]
I think they're talking about app not found... with the new version of electron you have to use 
var app = require('electron').app main.js also the browser window needs to require electron again, with a constructor, plus many other bugs that I am working to fix at the moment - the web view isn't working, using the URL bar - no go, etc etc etc.
