### ISSUE TITLE
Times New Roman everywhere!

### ISSUE THREAD

**Issue by towerofnix** [BookOwl/pion-browser#9]
![times-new-roman-is-bad](https://cloud.githubusercontent.com/assets/9948030/13538821/02d8bdde-e223-11e5-837f-c621e2834ecd.png)

**Comment by BookOwl** [comment]
What did you do!?!

**Comment by jeandrek** [comment]
Aaah

**Comment by towerofnix** [comment]
..I just ran Pion normally.

```
$ do_the_install_stuff
$ electron .
```

**Comment by towerofnix** [comment]
Is there a font that might not be installed on my Mac?

**Comment by towerofnix** [comment]
Nope, doesn't look like it, after all there's also Arial and such that are fallen back to if Oxygen won't work (and obviously I have Arial installed :P).

**Comment by BookOwl** [comment]
I fixed it. The problem was that I left out a comma in the font-family CSS rule.
